[[libtakum]]
arch = "aarch64"
git-tree-sha1 = "18ace1313038d67258834d8826644cdad6eac7b0"
os = "macos"

    [[libtakum.download]]
    sha256 = "93e7444f55e07f6bfe388eb040136faf0a3c162e6009aaa092b83fd3e3fa0c1e"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.1+0/libtakum.v0.1.1.aarch64-apple-darwin.tar.gz"
[[libtakum]]
arch = "aarch64"
git-tree-sha1 = "00d4d7afbde4929cabcb3bdd8a9282addfc546de"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "fc3441846966c9cd82d7de628eb2508492845ea0c17527347ba1b761e8c84e75"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.1+0/libtakum.v0.1.1.aarch64-linux-gnu.tar.gz"
[[libtakum]]
arch = "aarch64"
git-tree-sha1 = "34ea51740996f8b2d5d145301d6e1ff940856e65"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "6e8748711244b11faaea24a5b76834eeb65da39717d0d8cb7a48d64273513f4b"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.1+0/libtakum.v0.1.1.aarch64-linux-musl.tar.gz"
[[libtakum]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e6e077ee32f82aeb7f09a601ad848696fd61b9b1"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "9c99bbde2be6b062aa47e4a6f17689961e95b2d466faf71c986167e856bc1bac"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.1+0/libtakum.v0.1.1.armv6l-linux-gnueabihf.tar.gz"
[[libtakum]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d31b5fa6caa6aecc91aee02baaaf3fb3b82dfce1"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "74516e86ff8ca662d8472cb924919787932fed9eef96a9cf986734b5392aca5f"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.1+0/libtakum.v0.1.1.armv6l-linux-musleabihf.tar.gz"
[[libtakum]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c66b08dda73dadfb5ee1b594323d9aba0756c732"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "ae8c28dcc6e1d7ae358453a4ada0a3d37eaf8905636b2ea91bae9d421234e944"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.1+0/libtakum.v0.1.1.armv7l-linux-gnueabihf.tar.gz"
[[libtakum]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "127e6b42f6bc6e2d2c68065ee433f2a5eb6af314"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "8a9f5e7f2d30b280b7affba798bd942b923ae982621f84896963ddf2e1e72919"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.1+0/libtakum.v0.1.1.armv7l-linux-musleabihf.tar.gz"
[[libtakum]]
arch = "i686"
git-tree-sha1 = "4d7c44cb7e655f4289182ef856a0df3954b11942"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "e2bcd3800aa3f166c9bbeb2d06787b4148c5a7e480560482dd1da3f3c9122a2b"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.1+0/libtakum.v0.1.1.i686-linux-gnu.tar.gz"
[[libtakum]]
arch = "i686"
git-tree-sha1 = "ee4867def87af2435f6e7fc8aab7a6c41b2895b2"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "87ce569577ffcee71e2a7ac677649469004fe271400a93bb3491e57c903d74b0"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.1+0/libtakum.v0.1.1.i686-linux-musl.tar.gz"
[[libtakum]]
arch = "i686"
git-tree-sha1 = "8b90a68825616ed131973eec31b7bfde4a445618"
os = "windows"

    [[libtakum.download]]
    sha256 = "b53e5b86d8f1b750569e3d6d4d0d056ff6659aab7a38039c2698d000ae6955bc"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.1+0/libtakum.v0.1.1.i686-w64-mingw32.tar.gz"
[[libtakum]]
arch = "powerpc64le"
git-tree-sha1 = "1eafbdeba48938b5d0e583f28290f2000e93b6e3"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "e22f5317dc9e296a1bc9fa73923f50d8f923562e96dcbca022f8513ffdcc829a"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.1+0/libtakum.v0.1.1.powerpc64le-linux-gnu.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "af094c8d12dd9a90e96a43496fc62044e10f7ba5"
os = "macos"

    [[libtakum.download]]
    sha256 = "fb7af5d476e72c08dccb8adc90f09667e09e22ce6af083c4effd6aa6f04acbef"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.1+0/libtakum.v0.1.1.x86_64-apple-darwin.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "2012fb907cbf8c369db553b9da98969ffda30b2e"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "b36b9fb2ab37565acc845c2416ad2ef5869c8abad9b353500e23a2e850b9b7cc"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.1+0/libtakum.v0.1.1.x86_64-linux-gnu.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "dea24eb3694940dd3a383f8f99ab95a8679d3898"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "67cd2de5a679fc9ab62001f445f8ed7ad6eb0dd27ab5259ff964c318357cdc57"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.1+0/libtakum.v0.1.1.x86_64-linux-musl.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "fd5bc22173426eb4e7237b2fb13f226a9cf3a156"
os = "freebsd"

    [[libtakum.download]]
    sha256 = "79746172c4abf90415155287dabd8e97b3027d7fb154b9cc4cb3fcdfbadb12a9"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.1+0/libtakum.v0.1.1.x86_64-unknown-freebsd.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "72a350394f1f33af18873c644242139a4a1ff46b"
os = "windows"

    [[libtakum.download]]
    sha256 = "dd0e8de0054985ed789b09d4a044c03fca99a706c132c9c836bb939c9f15128c"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.1+0/libtakum.v0.1.1.x86_64-w64-mingw32.tar.gz"
