[[libtakum]]
arch = "aarch64"
git-tree-sha1 = "f8ca2ceda3e352389616f8342237633888e72f1b"
os = "macos"

    [[libtakum.download]]
    sha256 = "3110fee8cd2ad405b8e2e1e8d8bbf450eb76483817566b857a246a5e75a7e744"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.3.0+0/libtakum.v0.3.0.aarch64-apple-darwin.tar.gz"
[[libtakum]]
arch = "aarch64"
git-tree-sha1 = "7b05bbe7fbdf726069772149142f917bf36a05cb"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "cc03cb18bf0c8063ad7b954ea47b5840db667b9ee3032897fcfac104d0edb35b"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.3.0+0/libtakum.v0.3.0.aarch64-linux-gnu.tar.gz"
[[libtakum]]
arch = "aarch64"
git-tree-sha1 = "23e2fa28ff2c436684f5dd770dac2eeae81f248a"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "c3e2f0f4fa0e222d5d4e07b7bce9db17be609c20ad69ac9de75e8859a9aecb7a"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.3.0+0/libtakum.v0.3.0.aarch64-linux-musl.tar.gz"
[[libtakum]]
arch = "aarch64"
git-tree-sha1 = "d1c5050a4c8b7944d2118fdfd8f6ef0e9f0f2ece"
os = "freebsd"

    [[libtakum.download]]
    sha256 = "cda107a8264d84cbdaf20b457862068c5904e86451c97e2950ef18a433df76de"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.3.0+0/libtakum.v0.3.0.aarch64-unknown-freebsd.tar.gz"
[[libtakum]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "dbe529f63deb545a530ff6648ee5d0281a43f284"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "5ce22925f4195e0213c373115603f0d303d2068c07c2c11de082a2a8a79c0b7f"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.3.0+0/libtakum.v0.3.0.armv6l-linux-gnueabihf.tar.gz"
[[libtakum]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "60bdefe06c9b2b8e9a2fe096e0c86ddc04435374"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "b46250f901009c2faec08a0a3c1e1ec98adb7ed21f1c5cfca7616f34477760a3"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.3.0+0/libtakum.v0.3.0.armv6l-linux-musleabihf.tar.gz"
[[libtakum]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4fa49c0fc1167b9be055b6cfe745309f72187a49"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "551ff53642339769a33f4c4122c595271b79af1924b1491f47a45754998f38ae"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.3.0+0/libtakum.v0.3.0.armv7l-linux-gnueabihf.tar.gz"
[[libtakum]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7a88b72e765ba54f59fa4a703c6e7794a6f21d48"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "b9296ed012fddc356dfb6c9ad6cd4ae7794590f75cb071acf36ee42a862d9b53"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.3.0+0/libtakum.v0.3.0.armv7l-linux-musleabihf.tar.gz"
[[libtakum]]
arch = "i686"
git-tree-sha1 = "d0708da35321e1ba1011949e525740e5a2630732"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "995edc7f4419b9e2bda48d3b5991654ecd28218dad3f14d001ac14c55c768a4c"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.3.0+0/libtakum.v0.3.0.i686-linux-gnu.tar.gz"
[[libtakum]]
arch = "i686"
git-tree-sha1 = "032a0fe0615682f573c9d544ab786cae459ee75e"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "f9b9dc95d635bf77014709236e6bc7e9709c351b037da8189926a4784c065888"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.3.0+0/libtakum.v0.3.0.i686-linux-musl.tar.gz"
[[libtakum]]
arch = "i686"
git-tree-sha1 = "2d22594136cbc7c1cf15468f1a36a20529702aa7"
os = "windows"

    [[libtakum.download]]
    sha256 = "e6dfe5a49cb8c63b10812b9d4ae577f8d67ce28170a28898d4bf603a68fe8efc"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.3.0+0/libtakum.v0.3.0.i686-w64-mingw32.tar.gz"
[[libtakum]]
arch = "powerpc64le"
git-tree-sha1 = "bfc5e94d7e6f61e1b21a30291d7c90c35e7743b8"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "cb0411d34581f89d96449dbddd6bc1a02832939127c17beb58c071377c38d5d9"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.3.0+0/libtakum.v0.3.0.powerpc64le-linux-gnu.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "784bda60261a5f41d2f5c347cd0d56022ef5a2aa"
os = "macos"

    [[libtakum.download]]
    sha256 = "758d2688a9b95c5f9f12b240e988f644711c26fd789475dfb9140c2eaf815957"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.3.0+0/libtakum.v0.3.0.x86_64-apple-darwin.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "775c0e0543ef581aa7a28d48b994aa5a0ecadfa8"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "070ac988f91b915979e806b1cacb89c3317563a52926e7e17b263b2f825cc552"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.3.0+0/libtakum.v0.3.0.x86_64-linux-gnu.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "7be2de9c1d99f0794994346b2f42f41e684db03f"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "8ba95da991672c1b06dc33182713dc32b2b629e16e346af218ca786988e8ba69"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.3.0+0/libtakum.v0.3.0.x86_64-linux-musl.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "3945ed5dacd895a41c2b00e29cb92656cecaeff4"
os = "freebsd"

    [[libtakum.download]]
    sha256 = "1d2ac7453892b2ef4015f230a7d43e041c843bf5d590ba4602d74144b7ee93ab"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.3.0+0/libtakum.v0.3.0.x86_64-unknown-freebsd.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "69bd65f211cd334cc4548be07e0e898902e37e60"
os = "windows"

    [[libtakum.download]]
    sha256 = "2516dbec3a0c85100350ee16aa00524f84c8dbf0136d2b226f9906490d237ce7"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.3.0+0/libtakum.v0.3.0.x86_64-w64-mingw32.tar.gz"
