[[libtakum]]
arch = "aarch64"
git-tree-sha1 = "a9a9125ff5f20373960e766569f2aaaf421e75fd"
os = "macos"

    [[libtakum.download]]
    sha256 = "1a74589e0c1a58106966154fdb5c6a72009541b904f0a24530ea47d7baa64d86"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.0+0/libtakum.v0.1.0.aarch64-apple-darwin.tar.gz"
[[libtakum]]
arch = "aarch64"
git-tree-sha1 = "22a79f6e77b2e4e889a38c3bb64b07ac302282bf"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "df542b0e69026f511c2e0882214f78e03c6b1eae67690520c5b0c708c87f4210"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.0+0/libtakum.v0.1.0.aarch64-linux-gnu.tar.gz"
[[libtakum]]
arch = "aarch64"
git-tree-sha1 = "855e1a613ff333cb0fd8a323b194f44498edee0a"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "020dac371b7eb32f5e2d56fc05eeb71e7cba1b1cab381d5933cf560fbf089101"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.0+0/libtakum.v0.1.0.aarch64-linux-musl.tar.gz"
[[libtakum]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "491c8e5aea1aefd86d4349ca1823b6ab4c372dad"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "148f8ada341ede84e536822dc3ab89ce70012891e106fefe155d5643e9a195de"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.0+0/libtakum.v0.1.0.armv6l-linux-gnueabihf.tar.gz"
[[libtakum]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "657ceca3dafa1729bf4f006a699cd9c155e91134"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "a62e9f4c4e8f8c7c0986a93b312e48e950c7ba577fbecf8588bc744596a09415"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.0+0/libtakum.v0.1.0.armv6l-linux-musleabihf.tar.gz"
[[libtakum]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "adb49dcfade5514ed8cd53ef1de6747ab80e8209"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "cf48a6898cb1302d6b29a9203f45744afc803f51386def663fd45325cb2abcdf"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.0+0/libtakum.v0.1.0.armv7l-linux-gnueabihf.tar.gz"
[[libtakum]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5b8a4696ea0170c3765b46fe96d9e63e52120447"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "228b63ea41eaf0f33f032fd698a02940b3be4a27b431b86a21d408f8a1b03e97"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.0+0/libtakum.v0.1.0.armv7l-linux-musleabihf.tar.gz"
[[libtakum]]
arch = "i686"
git-tree-sha1 = "7a28d1a005cfeff960e82d40b62a338db47fe1ad"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "bee411dcc2e720b39edfb9fabc4f649989982ae2dd285cf7baacf616929803f9"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.0+0/libtakum.v0.1.0.i686-linux-gnu.tar.gz"
[[libtakum]]
arch = "i686"
git-tree-sha1 = "229dd21629dc837059876cdfcf00f539e0587d82"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "d9c157d72a293c0b63ccecf3b833782429551da778af8fcf482e4e69007f8139"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.0+0/libtakum.v0.1.0.i686-linux-musl.tar.gz"
[[libtakum]]
arch = "i686"
git-tree-sha1 = "1cc9b6f3498c4f40049bd62e39b0341b127a75c4"
os = "windows"

    [[libtakum.download]]
    sha256 = "33fca21af5433d4e86386ca3712f8980d9013bcc1c1fc962b8f7fa346d0c074f"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.0+0/libtakum.v0.1.0.i686-w64-mingw32.tar.gz"
[[libtakum]]
arch = "powerpc64le"
git-tree-sha1 = "e8d62dc214693cc3354e6995edaa8e6dbf453c2d"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "6b130ecd5acb824b29803b65c1b89c6080d6699593fb525ccf92b99a8aced091"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.0+0/libtakum.v0.1.0.powerpc64le-linux-gnu.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "4c598f0b7d2fbabcd9b6f23fbf615c4b7d640e88"
os = "macos"

    [[libtakum.download]]
    sha256 = "c9b6b08e019017414290cdd751ab916d78b90dba7615c0a17be5ac9f8716207d"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.0+0/libtakum.v0.1.0.x86_64-apple-darwin.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "854bf0272ac6e1604030296921dd15cf603877dd"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "65b251c3233d4f714d4016d5c6abfc85048b9fa9a20536776f8c9ae0bcbf2041"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.0+0/libtakum.v0.1.0.x86_64-linux-gnu.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "b7577536b971cea0d087ab5ec4d59a9c7cb312a1"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "c73e7bed976d98526a8859fad37740ec415497953ce6ea5bc150bc2f51369aa1"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.0+0/libtakum.v0.1.0.x86_64-linux-musl.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "88d39ab54a226ffbbfcd2d98cf8bb85afaad9dca"
os = "freebsd"

    [[libtakum.download]]
    sha256 = "474853ec0b3343b001210d6c4c8209f5dd84289add3581c085096b2faed07508"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.0+0/libtakum.v0.1.0.x86_64-unknown-freebsd.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "aa4d17edc78501eb9b10d5d19593f05e10b7fd25"
os = "windows"

    [[libtakum.download]]
    sha256 = "8ac43e9eeab5d4706a725862e7c5db418b48f1f67828c2b7a2bceb73bb4392e9"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.0+0/libtakum.v0.1.0.x86_64-w64-mingw32.tar.gz"
