[[libtakum]]
arch = "aarch64"
git-tree-sha1 = "e2c6d80e750c97e57746206a2d22bfb524fa9db7"
os = "macos"

    [[libtakum.download]]
    sha256 = "e03f5f545ba6220f4c20154d3b835a73004df0f6e6f2ce96a613e83c8b29abce"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v1.0.1+0/libtakum.v1.0.1.aarch64-apple-darwin.tar.gz"
[[libtakum]]
arch = "aarch64"
git-tree-sha1 = "07d352bb1e97b7cde640fe44ae2008fb89b1ac0b"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "bb4efcea73ad9439ff748ca19ccd8756eb32fa8194bb937e2d0a345790cc8bab"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v1.0.1+0/libtakum.v1.0.1.aarch64-linux-gnu.tar.gz"
[[libtakum]]
arch = "aarch64"
git-tree-sha1 = "2ec46fb6546c23de5ab6d46f04e0a9dd7ca9d521"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "8cc4eff87f7046685df1066a3e7b162200a9ed63ccf10c2bef41da55ff42797b"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v1.0.1+0/libtakum.v1.0.1.aarch64-linux-musl.tar.gz"
[[libtakum]]
arch = "aarch64"
git-tree-sha1 = "34c8697206b6c9f89144d0fbbe93075b57fc1273"
os = "freebsd"

    [[libtakum.download]]
    sha256 = "aa84f480e266d4a82250ba51c147420d432477b26a36b30b2379e3886c84786d"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v1.0.1+0/libtakum.v1.0.1.aarch64-unknown-freebsd.tar.gz"
[[libtakum]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "36b567da7104a486a5dda17691b4f44ed29ff0f7"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "3d65ecc1579bfec01dd9cd0269b671d5cf27fb6b90f1c35fd1b09470f2fc90d9"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v1.0.1+0/libtakum.v1.0.1.armv6l-linux-gnueabihf.tar.gz"
[[libtakum]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c1433df117aee06dfb1255fab7379173dce654b1"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "c5d87a1471c6ad700a88cb8b20c20c5fb1876c7d6579f518d5a664aeb6c4af73"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v1.0.1+0/libtakum.v1.0.1.armv6l-linux-musleabihf.tar.gz"
[[libtakum]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "deb70c4fa997d4bd8e85d3d50ce090d07779d242"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "7772c366814607390e6bb8a83e231cd153c83e4952fadd416e3e86995ab18aca"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v1.0.1+0/libtakum.v1.0.1.armv7l-linux-gnueabihf.tar.gz"
[[libtakum]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "31d36fc2a519da5935e781a2a0524b1ccce09b06"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "4a9c6da512dfe4afdc4ac2b0a349b40e33c07e965d490e79b3a7bdfa32059a7c"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v1.0.1+0/libtakum.v1.0.1.armv7l-linux-musleabihf.tar.gz"
[[libtakum]]
arch = "i686"
git-tree-sha1 = "71f1dc30dc043bf7a1dc225916b2b21a93c7e14a"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "03c8d3e3918bbda831bb14aa9a095805b2a0dc66827f778da5c4dbffe1e08935"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v1.0.1+0/libtakum.v1.0.1.i686-linux-gnu.tar.gz"
[[libtakum]]
arch = "i686"
git-tree-sha1 = "37917995eec3c3cc4871619bacbb6891de2a323f"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "d8647a42e55f24c92967e0a5751d004cd03f04b7c2fc1fdf9130e0757ecae83f"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v1.0.1+0/libtakum.v1.0.1.i686-linux-musl.tar.gz"
[[libtakum]]
arch = "i686"
git-tree-sha1 = "4048bed3a2289f06f354601c6eeae2015817a416"
os = "windows"

    [[libtakum.download]]
    sha256 = "dfe5d538e9de32f24f0141336e72992f88e99465e7ddc779ed62997b8f47c285"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v1.0.1+0/libtakum.v1.0.1.i686-w64-mingw32.tar.gz"
[[libtakum]]
arch = "powerpc64le"
git-tree-sha1 = "003c383747ddca6e50cca0a8b35d0872b8a04cd5"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "abb0bd4caa331f90b2a41961da0a44bc7b75c2641004f5e1b69307e5a7d11c59"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v1.0.1+0/libtakum.v1.0.1.powerpc64le-linux-gnu.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "7bfad72ceaa80f3f2b59dccf87d504a5dface4aa"
os = "macos"

    [[libtakum.download]]
    sha256 = "82d1ee95d1b168aec89f15360c8ad4b3c6b7ce84b29d6da3b6b99a98e05c092b"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v1.0.1+0/libtakum.v1.0.1.x86_64-apple-darwin.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "7ce6e8977cfa24ddc63a9f5d5f0a49be70fdf026"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "d0d2e45998bbda1d430b9784969d4f9d5e44c376568945376268bdaa8aeaaafb"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v1.0.1+0/libtakum.v1.0.1.x86_64-linux-gnu.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "7f48278ccc86df16e00b8014dd39615919873517"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "dadcae4f1d525c715a65b7bab5157426b889072da52e5c2431033f21d4c59c5f"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v1.0.1+0/libtakum.v1.0.1.x86_64-linux-musl.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "319d78bbbbc086176a70f648438e8c1632866643"
os = "freebsd"

    [[libtakum.download]]
    sha256 = "afe490cc0d3c6cc047724b366f67dbb376159cee84624058a04485a5c90517d0"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v1.0.1+0/libtakum.v1.0.1.x86_64-unknown-freebsd.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "edb0e4d351bf24b12ee21a2b62e01ff8985d153e"
os = "windows"

    [[libtakum.download]]
    sha256 = "bfeef9bb21117e9850ee6289dbcc22405cccf540169612e06052a288bac4e832"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v1.0.1+0/libtakum.v1.0.1.x86_64-w64-mingw32.tar.gz"
