[[libtakum]]
arch = "aarch64"
git-tree-sha1 = "328179042f58677dfc0ed63f64ce6aada4d65431"
os = "macos"

    [[libtakum.download]]
    sha256 = "837c4a1415b9a300bbcd88aa58188df4b7ed72a45e6d77948ad4ef8d7c1a35b1"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.1+0/libtakum.v0.5.1.aarch64-apple-darwin.tar.gz"
[[libtakum]]
arch = "aarch64"
git-tree-sha1 = "fca4a905d939f0f500a64ba1a5201a998a3e0547"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "c2113e694a05b72c6bc4a07728ef2f20d0f647d0496a60d7b50bb22ee2c8f079"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.1+0/libtakum.v0.5.1.aarch64-linux-gnu.tar.gz"
[[libtakum]]
arch = "aarch64"
git-tree-sha1 = "7437c6ba623b1f8183f64ec1256f87206dadefc8"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "acd0a38075bf7f9130e45e1a9030a37e0262eb550b67c66a17b277c05f013640"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.1+0/libtakum.v0.5.1.aarch64-linux-musl.tar.gz"
[[libtakum]]
arch = "aarch64"
git-tree-sha1 = "17ebea5983e765ceb1ff0d906036ab9ef531e4e9"
os = "freebsd"

    [[libtakum.download]]
    sha256 = "51f3c06519ad3be1d8e39c0929ad44d9bace5bc60638c3e5a1883d3d7b86cf49"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.1+0/libtakum.v0.5.1.aarch64-unknown-freebsd.tar.gz"
[[libtakum]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ca82cb79a92e6b171ed7169f57439f0b67eae3f4"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "7e9c97f23aa2c324e6b134ed33f8999d4d55e762e7877608d55e1befacc95945"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.1+0/libtakum.v0.5.1.armv6l-linux-gnueabihf.tar.gz"
[[libtakum]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7cce7c9750085cd77401c0904c514e9378d5df82"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "36060a514a035927559f854db2cd69d24bfd9ff050a3ed86449fc16db567f581"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.1+0/libtakum.v0.5.1.armv6l-linux-musleabihf.tar.gz"
[[libtakum]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "475dffab2147b9c1aaf9c870f40c347117e29716"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "58d6253af5fa905245634bbb48d0d0373af3d181969d43c733fd0c3d8d9203b1"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.1+0/libtakum.v0.5.1.armv7l-linux-gnueabihf.tar.gz"
[[libtakum]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "79d0e3f049465899d26cf48aa098ee4888961ee5"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "507bbf4de4eb242849116c578e8fb85a624a49b445796868eb7c51f79523bc77"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.1+0/libtakum.v0.5.1.armv7l-linux-musleabihf.tar.gz"
[[libtakum]]
arch = "i686"
git-tree-sha1 = "f9324cf7ea0fbdd382a1c0b6431ad7354da00cdf"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "52db86b2023e09594ea5fe44f1f9af95a1929bcaf1f91fda8a667d240987bef8"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.1+0/libtakum.v0.5.1.i686-linux-gnu.tar.gz"
[[libtakum]]
arch = "i686"
git-tree-sha1 = "32a102902e1a33381059bfd50e0135971c9be094"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "2589fdc0a8b85e216b23a8dde998eaf5746be45f8aa61a59b23b45e4dde622b0"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.1+0/libtakum.v0.5.1.i686-linux-musl.tar.gz"
[[libtakum]]
arch = "i686"
git-tree-sha1 = "e24090ff7558602aff2c2669f5a8a10eab77b919"
os = "windows"

    [[libtakum.download]]
    sha256 = "30d240b0a0e047cbfb58fba671b5b2b98bab3317c46b0749c4cb65be10e6a608"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.1+0/libtakum.v0.5.1.i686-w64-mingw32.tar.gz"
[[libtakum]]
arch = "powerpc64le"
git-tree-sha1 = "d234900910f02a065f6de9ee8e8716eeb315859a"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "8c130e07f58f03298ad369ba9b2b7785b6af28d4b34b0f380ec3cd70461808da"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.1+0/libtakum.v0.5.1.powerpc64le-linux-gnu.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "f5051cd0b138e510702563b1fe00dcade801eb44"
os = "macos"

    [[libtakum.download]]
    sha256 = "e8c1b9d673289461dd333701e2c499601cd77be4228165abfcb1ede040f674a6"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.1+0/libtakum.v0.5.1.x86_64-apple-darwin.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "705c58438c63e61ed9dcdbf273e01794810fe1c2"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "6fad475625f5f2175f0c59e36d3e34629678037fe48317d1bb6f3b5951925a28"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.1+0/libtakum.v0.5.1.x86_64-linux-gnu.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "cfac9db13afe04d2d15c350f8a3d6567665169fc"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "2a91d68d06b1f69773d71dd7e7f5c8c328a262c56a613adeb66a5d069d3de293"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.1+0/libtakum.v0.5.1.x86_64-linux-musl.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "2e5de6ecb6219bd33beba74d81709ebc825b71c6"
os = "freebsd"

    [[libtakum.download]]
    sha256 = "f1e8fa39a4469e41e2ac2e6966150434ed240f2782675e17790a2d336dbc48d0"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.1+0/libtakum.v0.5.1.x86_64-unknown-freebsd.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "a1bb56820c972d54d16c1c078b82e4ff672d5b08"
os = "windows"

    [[libtakum.download]]
    sha256 = "69ed3990f438dbc82305d416a411c3a700f08cdf1b5c380929868ef2065b0311"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.1+0/libtakum.v0.5.1.x86_64-w64-mingw32.tar.gz"
