[[libtakum]]
arch = "aarch64"
git-tree-sha1 = "6eb1a45ec0c33d2af693babb61259d37f49aa0e1"
os = "macos"

    [[libtakum.download]]
    sha256 = "b911741aa5637988eef625faf2242eef4f8e5e990f4a832943e84ddfda624857"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.2+0/libtakum.v0.2.2.aarch64-apple-darwin.tar.gz"
[[libtakum]]
arch = "aarch64"
git-tree-sha1 = "e8403aa084a3795eb267d05a8b9cf3bff9571ce5"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "2a1f4a9a7b0311d7e6e2ca6543d7bf26bec26053981113db0b0fed4d141b8c0d"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.2+0/libtakum.v0.2.2.aarch64-linux-gnu.tar.gz"
[[libtakum]]
arch = "aarch64"
git-tree-sha1 = "8d03df722d0d5d9f615d43706647a4fa59821e08"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "c809352a15ca7f5e0609e4f53794ffa9c05ccdda2617026cde54d7c02c3ea2b7"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.2+0/libtakum.v0.2.2.aarch64-linux-musl.tar.gz"
[[libtakum]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ea5f1f6362dcf37b1f513a69005974c22d64bc58"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "86a2293aaf7afebc19a4fb6c9bdb059e932e42e022f3805d75c73436812ccbcc"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.2+0/libtakum.v0.2.2.armv6l-linux-gnueabihf.tar.gz"
[[libtakum]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "22b419b6a8913e27055703e9724867d35406a5ac"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "ca4775209a2ead696659b5fda344967e8e7012a6b2c211155e42ac47b8f38757"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.2+0/libtakum.v0.2.2.armv6l-linux-musleabihf.tar.gz"
[[libtakum]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b3a1d61c89cb66973034b64786e7c0f07e4b9ad5"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "2729f5ace75e0f138bed2e1e875507d27d354aacea2114edba9edb0bdb94d8d2"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.2+0/libtakum.v0.2.2.armv7l-linux-gnueabihf.tar.gz"
[[libtakum]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4af1d0c8feebf89e0de798fe244111e0b75d11f9"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "c489dd34e98ff16adf7ffbff23ac9465e7817c86448b29ff1fc53496ac59280b"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.2+0/libtakum.v0.2.2.armv7l-linux-musleabihf.tar.gz"
[[libtakum]]
arch = "i686"
git-tree-sha1 = "b8dceb2254340ddd9dac6bda6640cfbfaedba2fb"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "9ff3fe9b550ac1a0d2936b6daba4cd043d615762567ecb0c02f68c16a53ace93"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.2+0/libtakum.v0.2.2.i686-linux-gnu.tar.gz"
[[libtakum]]
arch = "i686"
git-tree-sha1 = "e252bd67bbb00a2ed1bb0a37fbf69bbf2e116f50"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "e8107816b8a2d3bf7851f4fab6d753c87cde2f1a9b827a807cd028207be509d9"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.2+0/libtakum.v0.2.2.i686-linux-musl.tar.gz"
[[libtakum]]
arch = "i686"
git-tree-sha1 = "5d1db8935bcb1f9cec404fbf8732d911df3a95e1"
os = "windows"

    [[libtakum.download]]
    sha256 = "e41e7514029ae279129c10446448fbbe6e41051f735ef9868aafc3e9459d9a2e"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.2+0/libtakum.v0.2.2.i686-w64-mingw32.tar.gz"
[[libtakum]]
arch = "powerpc64le"
git-tree-sha1 = "de14dd2931e0a85ee59edcf75f3e967785ce20c1"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "0a3d6585156ec4a32564d7cb1746b6f7a49e6b253827a1fe0c496109777e659d"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.2+0/libtakum.v0.2.2.powerpc64le-linux-gnu.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "8fba609cb5296cf9a18794a574bedf89da6d08a0"
os = "macos"

    [[libtakum.download]]
    sha256 = "37c4fe621e0efec58da7df0953971fdd25c3523e46a9e2e2486f7f7941fdd3be"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.2+0/libtakum.v0.2.2.x86_64-apple-darwin.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "68a7414a06ec79e5e80e5203bff23644db808561"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "bef1276f70d1aacd4e21a5c50981ca00d8153e8bbb3e8ca8dd6dd2fef1681242"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.2+0/libtakum.v0.2.2.x86_64-linux-gnu.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "5dc55ce4a95a37c2ed082c77fc9a8292f2e29d30"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "a75ec5b38b5dbf85fe970f073a63183dff84d655efc9a60615a1421221036cc2"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.2+0/libtakum.v0.2.2.x86_64-linux-musl.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "e32e1f4767d9222adc984dde4be65c0a2a4cc71e"
os = "freebsd"

    [[libtakum.download]]
    sha256 = "268467950046522b388ab74085876d08edc223bb2ed23c183b4dea7138cdf10f"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.2+0/libtakum.v0.2.2.x86_64-unknown-freebsd.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "6a3025d088deb56431f7668119b3a56267596bf8"
os = "windows"

    [[libtakum.download]]
    sha256 = "82044f89b4756c43a0913e037a8a998529d0ff67ab8d492ec7c4c0dce1ac3636"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.2+0/libtakum.v0.2.2.x86_64-w64-mingw32.tar.gz"
