[[libtakum]]
arch = "aarch64"
git-tree-sha1 = "e078df48078c04209847d372af6ac3d5059ffefc"
os = "macos"

    [[libtakum.download]]
    sha256 = "9496336f0cb1d677761f16a73d7758392f0c5da39a4073d4cd8aa64b7665f2d5"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v1.0.0+0/libtakum.v1.0.0.aarch64-apple-darwin.tar.gz"
[[libtakum]]
arch = "aarch64"
git-tree-sha1 = "5ea34d8e1c90dc947faa2f9ef1eaa652c38c4e53"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "f64fc14acc65f0b07e4b09494403a37a0fa0270d19b1cc996bc81bfdee61a561"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v1.0.0+0/libtakum.v1.0.0.aarch64-linux-gnu.tar.gz"
[[libtakum]]
arch = "aarch64"
git-tree-sha1 = "f657ee3c76b997c2f6c427a25a9bb80b40f1ef81"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "4788bc7b260f9fae8af6838ad7cb4dc0386a1c581a22ad7b887d15431401a2e6"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v1.0.0+0/libtakum.v1.0.0.aarch64-linux-musl.tar.gz"
[[libtakum]]
arch = "aarch64"
git-tree-sha1 = "777a57822f63467554c7f7d7199532ed073a1ce9"
os = "freebsd"

    [[libtakum.download]]
    sha256 = "ae7d4d06616244417dff02380d13796fac5f65fee199e2edae85bdeb64290d23"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v1.0.0+0/libtakum.v1.0.0.aarch64-unknown-freebsd.tar.gz"
[[libtakum]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7da31c5bea502f72d2afac460f9ae26e64cc3334"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "bd6b38ef75a5c5d9d9ae31de667278033e41a648c0a6a60df0c4a38d0f25ee31"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v1.0.0+0/libtakum.v1.0.0.armv6l-linux-gnueabihf.tar.gz"
[[libtakum]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "42ec916fa058e267206ffd3299448c23666a0438"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "c88277b521fc57d1bc44bdc81e279738188ed65628289e3ab678d9e47a586a03"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v1.0.0+0/libtakum.v1.0.0.armv6l-linux-musleabihf.tar.gz"
[[libtakum]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "285d4d4ab7843f755c397b451e1c9a21eae0b2f1"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "1689822329479a02fd721169e6511e6428e1c49446d0336d94d13b19c02c01f7"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v1.0.0+0/libtakum.v1.0.0.armv7l-linux-gnueabihf.tar.gz"
[[libtakum]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "abc7b8c9d801b5bd6bd8bd36ad427e748633c887"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "9b5348bf9c744c0d25033bc444ba7845bdafeca06af5a84b0b02995a39a89f81"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v1.0.0+0/libtakum.v1.0.0.armv7l-linux-musleabihf.tar.gz"
[[libtakum]]
arch = "i686"
git-tree-sha1 = "cf56ef85bfc0ee069e5318cebd16b4aec6d86b0a"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "d565dfb47bd96fb3d5b60f2e90e3684395d6248f765c3fe247d61fa297213d21"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v1.0.0+0/libtakum.v1.0.0.i686-linux-gnu.tar.gz"
[[libtakum]]
arch = "i686"
git-tree-sha1 = "ba0da2bcccb29b268accd4c48faf3ad9a23c4a78"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "ce4358ffc73fdd6521da7c995cde15c5df25691f0f902e4fcb1fb9d348e2e7ea"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v1.0.0+0/libtakum.v1.0.0.i686-linux-musl.tar.gz"
[[libtakum]]
arch = "i686"
git-tree-sha1 = "3abf1b0e7431fdbbf34157db2ec863b91e0c8f85"
os = "windows"

    [[libtakum.download]]
    sha256 = "82ec8296d7c58b041ab18fd0ae148ecb4c09209c066c1d486a3425f6ca4cf716"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v1.0.0+0/libtakum.v1.0.0.i686-w64-mingw32.tar.gz"
[[libtakum]]
arch = "powerpc64le"
git-tree-sha1 = "b380b87787b3a8fc3a041dc2d1d24958d86b8daf"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "cd9ed95dedcab6746b97fbe61cb9e21438b3bbf10be93fbd4f264ee7b6fae6c5"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v1.0.0+0/libtakum.v1.0.0.powerpc64le-linux-gnu.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "b1f8611a11e473cf3baa0beebd94ae2e6fff62c4"
os = "macos"

    [[libtakum.download]]
    sha256 = "75cb826522904276d2e11e371f641d3c196fea3b3c4d79cd1c9aee79bccb4f90"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v1.0.0+0/libtakum.v1.0.0.x86_64-apple-darwin.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "ef286f4f1c1fb19fbc37f5d6bc421836357e5b55"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "80c19a2d85904025c1bde79b75626c4bc7d5690c153ce80f7b2c6f0645b784dc"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v1.0.0+0/libtakum.v1.0.0.x86_64-linux-gnu.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "fa9e28073cce448de2986605f937f8c4adbd3fce"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "cd9aeca9123e9ebce22cc226a4366b9a95b399d9457c9882b020c2b85488c974"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v1.0.0+0/libtakum.v1.0.0.x86_64-linux-musl.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "a67849c11522919d090ae0ba1092ebebe767a19a"
os = "freebsd"

    [[libtakum.download]]
    sha256 = "de8b2b46c1e1c445fec187a460a80e18bdb74ee211d27c75bff6caac7037716a"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v1.0.0+0/libtakum.v1.0.0.x86_64-unknown-freebsd.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "62192a31771ffe1da85d5aaf8c3c96bcd252e2d0"
os = "windows"

    [[libtakum.download]]
    sha256 = "591f5f789f8fd344dee0c81f088fc052a67dcf43f9af670618ebc635b0f0eaee"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v1.0.0+0/libtakum.v1.0.0.x86_64-w64-mingw32.tar.gz"
