[[libtakum]]
arch = "aarch64"
git-tree-sha1 = "1796d88646e6d6b15b0518a5478f470e2e3a667f"
os = "macos"

    [[libtakum.download]]
    sha256 = "5c207d2132fab2303bae4eec0a1988af870ee9df1bd7c6ad55d5a814f0ba674c"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.1+0/libtakum.v0.2.1.aarch64-apple-darwin.tar.gz"
[[libtakum]]
arch = "aarch64"
git-tree-sha1 = "82ee6750682d72957b49500a6965b5fb26a6910b"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "3e0e5a9f2a24167f9267e62bb4b72784a55088bc1d8ce5bb3ee9129895fc82a6"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.1+0/libtakum.v0.2.1.aarch64-linux-gnu.tar.gz"
[[libtakum]]
arch = "aarch64"
git-tree-sha1 = "9a5e9ef7e42db0e296c44d282be026ab669522ce"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "228a549550bbe0dd557d359a6b3b40b334750c0cb8bdfcf86363f536b071849a"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.1+0/libtakum.v0.2.1.aarch64-linux-musl.tar.gz"
[[libtakum]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "76339182e5e7e4eabae5b92ec7a06b53e4b1f9eb"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "746816d8b75c0e6f17e17efd593039e072fd9d94cba832bc8cb66acbcfd7e9de"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.1+0/libtakum.v0.2.1.armv6l-linux-gnueabihf.tar.gz"
[[libtakum]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a21f9974e756a248b875adf151b5d8a6eb27adc3"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "b555056bf56d56870b5a061122b1b9d8ff4c06f54d121551e8bd4b22bce196ab"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.1+0/libtakum.v0.2.1.armv6l-linux-musleabihf.tar.gz"
[[libtakum]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f9907d20f831fcb998ac1615d6cdb3907589bbe6"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "754eb1f5c1655a535628959fe646b6623fe4d02591a180cf8a472da9ae160dab"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.1+0/libtakum.v0.2.1.armv7l-linux-gnueabihf.tar.gz"
[[libtakum]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4bc47f6519b03cb30ca3f39c19f019218dadea64"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "dcd9aa15b23a10830863ea8badb9ff5dce6b9553573ed512a9ae707e722f3f17"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.1+0/libtakum.v0.2.1.armv7l-linux-musleabihf.tar.gz"
[[libtakum]]
arch = "i686"
git-tree-sha1 = "9d134051b91247e8880f16dcf98213d2dbf752f9"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "feb8922102020b2d698f4508c7c53f6695d1078f6e66206f616284d675ed5d7f"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.1+0/libtakum.v0.2.1.i686-linux-gnu.tar.gz"
[[libtakum]]
arch = "i686"
git-tree-sha1 = "04cf226d91cb8d5e990d290c5fbc2cd1af37d18f"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "d8da4101ae2cd58f0840b0f5b0f9fc5962a5456508b5791119840cd2711506b9"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.1+0/libtakum.v0.2.1.i686-linux-musl.tar.gz"
[[libtakum]]
arch = "i686"
git-tree-sha1 = "d3066ab24fae7bb5082c715519bc36c762f4a7fc"
os = "windows"

    [[libtakum.download]]
    sha256 = "ee89ba00cf014ccf74c7e6cb5c94b5c15d8a9b0c755b7a46255509af3569a58c"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.1+0/libtakum.v0.2.1.i686-w64-mingw32.tar.gz"
[[libtakum]]
arch = "powerpc64le"
git-tree-sha1 = "8f3e81c96aeae4b1e20e0f4b0fd602f587db68be"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "ddfd98be2f08c66e09f62eb782fe3badb7a4d942e9bb1100bb4a7bb98ef0b89c"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.1+0/libtakum.v0.2.1.powerpc64le-linux-gnu.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "9b3a76bfd91c09408968e4a7dd58e334828714ca"
os = "macos"

    [[libtakum.download]]
    sha256 = "41e13a3c47e3ac10f45a102a56bf23976d96a649a3839ce84bcd2c76e9453c31"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.1+0/libtakum.v0.2.1.x86_64-apple-darwin.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "2543ecf0fc5814039cf3fc868f719ddf55e5d42e"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "a13b5840e3c4e4ceb70c60d3db451e282f57363b6b6a8639f1c2fe08d0b4441c"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.1+0/libtakum.v0.2.1.x86_64-linux-gnu.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "5071c8e132baa2d50e17bc4a72147cdb6585c0ba"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "12f878761a223959bb9f90af79757d828ba8e350ef4f6fc9ccf0985298646ea4"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.1+0/libtakum.v0.2.1.x86_64-linux-musl.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "1bf8b19cebc9ae0f7d12b5700d9e792327236c60"
os = "freebsd"

    [[libtakum.download]]
    sha256 = "1e124638bba2c9a2f83d9e145982f2fd5123e984c1bfa3b88d8b1f83f8702d85"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.1+0/libtakum.v0.2.1.x86_64-unknown-freebsd.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "4308b1907dcceed8396d53770c3536ea55a10c6a"
os = "windows"

    [[libtakum.download]]
    sha256 = "75cbb1c58788d59893b9d975dd562fc6791c2eaaf6209f1ea373c89b0bb62b88"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.1+0/libtakum.v0.2.1.x86_64-w64-mingw32.tar.gz"
