[[libtakum]]
arch = "aarch64"
git-tree-sha1 = "00911e8600f0b4f7252b6f8ec8fa21c6a3ba392e"
os = "macos"

    [[libtakum.download]]
    sha256 = "fbae425158b46fe07b09760dfd45ee135f221197141414a2719808236af12ada"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.2+0/libtakum.v0.5.2.aarch64-apple-darwin.tar.gz"
[[libtakum]]
arch = "aarch64"
git-tree-sha1 = "a84a8005d99c279acb6860b4cb30a66e7c838a0f"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "416fef9d399efba73580361df7db886cfb9dad5261c6dfdf3d35c5dad662dc3a"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.2+0/libtakum.v0.5.2.aarch64-linux-gnu.tar.gz"
[[libtakum]]
arch = "aarch64"
git-tree-sha1 = "ac754052957cd8d6a13cc0a7bcb334130fb456ff"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "5c19dc45e03480a9eb15bbfb1ce1ba739024e50f3ec257e608b7442c952b878a"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.2+0/libtakum.v0.5.2.aarch64-linux-musl.tar.gz"
[[libtakum]]
arch = "aarch64"
git-tree-sha1 = "f1b21aea775e5fbd27ebfd30b75bec9931bb18a0"
os = "freebsd"

    [[libtakum.download]]
    sha256 = "901a2e66d50bc888e3fed3f2f764187cccb36b9a54950ccfbc248b6ad104362f"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.2+0/libtakum.v0.5.2.aarch64-unknown-freebsd.tar.gz"
[[libtakum]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2580fdb1d365130b5c1ad32583a5947e92487c2d"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "8e1bf2dc5acda40047740f971d188d973edc337d63639b654347265f10a7f5c7"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.2+0/libtakum.v0.5.2.armv6l-linux-gnueabihf.tar.gz"
[[libtakum]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d2bc21613076473885ed1fd72efecb5ae82f4d92"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "3c6c1047663ef1fad73a38c7bf2ae3fa997c4df1a1f54b3cee36bc4eed27579e"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.2+0/libtakum.v0.5.2.armv6l-linux-musleabihf.tar.gz"
[[libtakum]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "594cf84962972086d6a49f416d025020689bd2f1"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "2b83eb84b131b2b18c7e2edacda69ead1c19403f0c8cc1ad6b3ae843785be8a6"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.2+0/libtakum.v0.5.2.armv7l-linux-gnueabihf.tar.gz"
[[libtakum]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8d68bcf5a8dc1d84e9f906bf261a443dbf82b350"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "d244e9c1051e5b5b630b83730cd21bc7efbbf8276ec8cb4f43c6e7a4efbccba6"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.2+0/libtakum.v0.5.2.armv7l-linux-musleabihf.tar.gz"
[[libtakum]]
arch = "i686"
git-tree-sha1 = "5083bf1bb87b6ad03a6b36c299316351b5085863"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "59cb9d5a5e84744a3314c757c2c18c714899455e8982d25610e5204534f9d317"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.2+0/libtakum.v0.5.2.i686-linux-gnu.tar.gz"
[[libtakum]]
arch = "i686"
git-tree-sha1 = "0dbce65bbaf18c8b3384642785a9685cb81aefa6"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "53ceda9ace8e20b2baccc400737b3e4dbb987c90846552ff1d1f63b0b00db031"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.2+0/libtakum.v0.5.2.i686-linux-musl.tar.gz"
[[libtakum]]
arch = "i686"
git-tree-sha1 = "35cd5fca65f36f8e83f39817a2e4f6f0230817a4"
os = "windows"

    [[libtakum.download]]
    sha256 = "0ca1b485f2178fe40deed2118d557f54f93e2471fc5335839689282fb4a2b0c8"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.2+0/libtakum.v0.5.2.i686-w64-mingw32.tar.gz"
[[libtakum]]
arch = "powerpc64le"
git-tree-sha1 = "87baee8c900eae94821b58dbc93da321862c4025"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "d87ef7c6db71a1b8a0bf5a0c1104348f3997e485d021cbf827510b5e678a1c9e"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.2+0/libtakum.v0.5.2.powerpc64le-linux-gnu.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "2be3526ac90e96ebfec94cfc7399b331169e2950"
os = "macos"

    [[libtakum.download]]
    sha256 = "9e8dd77287c618e9a5e9d16266a9453d814a4f121414ae5162a8bf3388e1e6e0"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.2+0/libtakum.v0.5.2.x86_64-apple-darwin.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "2f4bf2e153092efc0f3dfde97c9c0b77cd74c55c"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "49779c8ece257fc85ad308596d574cf3e26e2621a2885701825eb43d4c86bb03"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.2+0/libtakum.v0.5.2.x86_64-linux-gnu.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "545a90980ece948381f43820661037bb49eac2ee"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "a7072992093af2545f75cdb3348b625f3dc54c0da3b78c4a082760e5f89e435f"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.2+0/libtakum.v0.5.2.x86_64-linux-musl.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "2f385a0f21304efd2545c16d42bc765396966cdf"
os = "freebsd"

    [[libtakum.download]]
    sha256 = "643562ee7fae0d89f399c86e071640f192877b3f5e99c6606a499cf6038df4cb"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.2+0/libtakum.v0.5.2.x86_64-unknown-freebsd.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "2cdfa369df1f5eb6c433e6ced2c0da19f1a0b16a"
os = "windows"

    [[libtakum.download]]
    sha256 = "bf474c6154d959346bba3f51996ea927fda9648c0bfa3e0240d00df1d78556e4"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.2+0/libtakum.v0.5.2.x86_64-w64-mingw32.tar.gz"
