[[libtakum]]
arch = "aarch64"
git-tree-sha1 = "a600d96da92cf8e195eaf455ca9252943013c4d2"
os = "macos"

    [[libtakum.download]]
    sha256 = "45b6add1d3de6947081774e852a1f0f043d6cd8165485e04a80fcdf70ea24db2"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.2+0/libtakum.v0.1.2.aarch64-apple-darwin.tar.gz"
[[libtakum]]
arch = "aarch64"
git-tree-sha1 = "d75ec897be5d6736980da21faec01617c5cdd7e7"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "15a72639867d4e836d5d41fd96da7ff066663bbddf605b9ed0c33b79e90f696f"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.2+0/libtakum.v0.1.2.aarch64-linux-gnu.tar.gz"
[[libtakum]]
arch = "aarch64"
git-tree-sha1 = "1b5b2c50e1cc9aa8709bcb02da0e86c5f309d2fe"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "45aa4ddbf2ebab56251d45e0457eaecf1e84e73c5430ae56582b1d728cd746f1"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.2+0/libtakum.v0.1.2.aarch64-linux-musl.tar.gz"
[[libtakum]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "20a6ec2392312041f4fd31539fb1f57681623de9"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "aa4cc8aaf7ffe375df0d653f81a52896f20d6d087712cf1b589b35e7f0205769"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.2+0/libtakum.v0.1.2.armv6l-linux-gnueabihf.tar.gz"
[[libtakum]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d574fe6d8e1acf9ef0ef0baa504e18a903fc19ef"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "df73604384dbfabc7b4d63bd0297bb031ddf7872d3450f05ac2a3f0513703170"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.2+0/libtakum.v0.1.2.armv6l-linux-musleabihf.tar.gz"
[[libtakum]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "060a1c8e2c3a44b5a4b7c06229fca36569bf82ca"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "3832492b18601ff7ba02ae746364b9dbbeb62338a7d3697176be7513ef3406ff"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.2+0/libtakum.v0.1.2.armv7l-linux-gnueabihf.tar.gz"
[[libtakum]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e284d259d6dc80dacb716a67664b940b02a16414"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "7135d16e0ca6324fec3c0eee6671faeb5a5a9cbd867b1320a1a35599e11db1ff"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.2+0/libtakum.v0.1.2.armv7l-linux-musleabihf.tar.gz"
[[libtakum]]
arch = "i686"
git-tree-sha1 = "a143d657478c3d886518f8e95dbf196b97604808"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "2c797eb20ff8564765935df87c6a7c71cf46215d1f7ba3942ce43ca172ab433a"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.2+0/libtakum.v0.1.2.i686-linux-gnu.tar.gz"
[[libtakum]]
arch = "i686"
git-tree-sha1 = "27ca65290f03b1f34bc53dfc88c09f9dbb5df51c"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "01c849c6eace9b3985f97edb05397fcd2c46344c37ce557627bffb87b93592f8"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.2+0/libtakum.v0.1.2.i686-linux-musl.tar.gz"
[[libtakum]]
arch = "i686"
git-tree-sha1 = "de05aefea3f21b53a9910914839b1375d6fc57b2"
os = "windows"

    [[libtakum.download]]
    sha256 = "4c8cdde138c77c7a3ea5ca5793d4cc77260aa93c53a6b037cfee38020dd896ed"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.2+0/libtakum.v0.1.2.i686-w64-mingw32.tar.gz"
[[libtakum]]
arch = "powerpc64le"
git-tree-sha1 = "325e9cce55508ed32332ea8abaee33c84899891d"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "7be7d228bddfc39d2610fecea03e7591e19aec2e99c4a3e6c208f9d67908d88c"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.2+0/libtakum.v0.1.2.powerpc64le-linux-gnu.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "7e8c3e8d1230e07ebb15626737e8c026013b75a7"
os = "macos"

    [[libtakum.download]]
    sha256 = "5c8a08ac407a108e5986dc5645ffa3c90f5bde48e3cdf36d165f144f6e4eeef0"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.2+0/libtakum.v0.1.2.x86_64-apple-darwin.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "fce68f9742ec793ccb47addbb68932aff8e9613d"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "3fe31b88cd4c5acd409be31ad653dcbd1628a93dfcb3b4ee3e03d4153e4bbe91"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.2+0/libtakum.v0.1.2.x86_64-linux-gnu.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "da445cccac9423c9643dd420283251d194be6a5d"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "a2700ddc06176de907317e61df1a5c3dadc40fd1475f9472bf7f6d0d2d645023"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.2+0/libtakum.v0.1.2.x86_64-linux-musl.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "6bd3c2bd20186b6d2945f8ee362e751d8bfb3823"
os = "freebsd"

    [[libtakum.download]]
    sha256 = "09c0ed0e5dc9152aacade6230f7103648c0b03c697a9b6e08224bf897b3a38e9"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.2+0/libtakum.v0.1.2.x86_64-unknown-freebsd.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "5b0372d4987304880e87666dcb4385c69ea21206"
os = "windows"

    [[libtakum.download]]
    sha256 = "46092263525610296de1e47d929e22ff4e52461b2fede51697929fe02f726bdb"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.1.2+0/libtakum.v0.1.2.x86_64-w64-mingw32.tar.gz"
