[[libtakum]]
arch = "aarch64"
git-tree-sha1 = "d5bcfece308877b382e2ef84d46afb3c69e717b0"
os = "macos"

    [[libtakum.download]]
    sha256 = "5c2ca779a68254222f67bbf92333aa7427c63be90d4791ba7be2b2a626c8b3ec"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.0+0/libtakum.v0.5.0.aarch64-apple-darwin.tar.gz"
[[libtakum]]
arch = "aarch64"
git-tree-sha1 = "b55a86f25f5c674dd849dea778a17812e360df3a"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "eda047d68d7892f8ab878fe34bafd1f22c0cce05f01789c67548ae1ed56a93c6"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.0+0/libtakum.v0.5.0.aarch64-linux-gnu.tar.gz"
[[libtakum]]
arch = "aarch64"
git-tree-sha1 = "83ca58924251b71832e6c1df4ce453a941aa3a94"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "de4b7b7a0ba8c1a3c977010e9ccda3ea06f4813c20596e9ae2682f4910b10362"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.0+0/libtakum.v0.5.0.aarch64-linux-musl.tar.gz"
[[libtakum]]
arch = "aarch64"
git-tree-sha1 = "45331177fbac741b769db6be2b413784e98ecb02"
os = "freebsd"

    [[libtakum.download]]
    sha256 = "5a3b4dadf1d9c09ca5a7e4d8924c6deddca1b51969c62d944cc486233f1e5599"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.0+0/libtakum.v0.5.0.aarch64-unknown-freebsd.tar.gz"
[[libtakum]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "54012d5bc1d87cd18e599b943a28f5e52e7c5407"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "9dc88b21c7f5cceee53cc0be71dcad57b2a80ac5a0593815ef4c61c94316aaa2"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.0+0/libtakum.v0.5.0.armv6l-linux-gnueabihf.tar.gz"
[[libtakum]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2ab00cffb126a018ba8e9a13657f82672bc8db65"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "f8790796d26afb8e0b37eb360dc49ce0c932d9c470f9afd8d0bba47d684e752c"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.0+0/libtakum.v0.5.0.armv6l-linux-musleabihf.tar.gz"
[[libtakum]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5e5d784d54a2fb841b2e2c62c36972478d336e6f"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "3cab33df2863ff6735945f8f9f816427f6f0ff674e1fa1cb9d8476ab521db289"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.0+0/libtakum.v0.5.0.armv7l-linux-gnueabihf.tar.gz"
[[libtakum]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "917be7f633d48ec4fc7833eb11aff8cc3bc5efaa"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "e34f0d325f52fb8e8fcc69bb78ed5f537133ef3656ee17ad7995b1b24fe97b9b"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.0+0/libtakum.v0.5.0.armv7l-linux-musleabihf.tar.gz"
[[libtakum]]
arch = "i686"
git-tree-sha1 = "74c6645a47f9348fe53c5d7e03f64f8f1e6089bf"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "536c6abfebf5276629d219a8442f8eb788c87006ac57402db22cbbfe22310439"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.0+0/libtakum.v0.5.0.i686-linux-gnu.tar.gz"
[[libtakum]]
arch = "i686"
git-tree-sha1 = "cada8f1ca1ad2a90a5b5e06d42936a119985b0b6"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "a7f87665f3c45a84870854dccb5856a789eb5d81ff224444f961628234206e08"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.0+0/libtakum.v0.5.0.i686-linux-musl.tar.gz"
[[libtakum]]
arch = "i686"
git-tree-sha1 = "04b2d4c71d003e72d37bf8a3f03be26b36171c1e"
os = "windows"

    [[libtakum.download]]
    sha256 = "4056dbd04558851f5b04ce7d111bea839f6f7ac8ae6d5c543196829afe071c8c"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.0+0/libtakum.v0.5.0.i686-w64-mingw32.tar.gz"
[[libtakum]]
arch = "powerpc64le"
git-tree-sha1 = "538067f84eef108f0c2a0a65997ff68913146683"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "13bb40f3819880e37ff7f0f39ff36fbc57ca54c6ef06c9eb1bba11eaaa907cb7"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.0+0/libtakum.v0.5.0.powerpc64le-linux-gnu.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "eb489041a67c6fd371268747f08618b7cf538731"
os = "macos"

    [[libtakum.download]]
    sha256 = "20151c4c1d32d321c98a724d7097176649cf90d3d4124c9744a4b072d4911fdf"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.0+0/libtakum.v0.5.0.x86_64-apple-darwin.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "2e16e220f14d544872d418015412b4246be05ff6"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "540536b858be5de7c9819705344adfd8b01c0efcecd16e40a0e1267723a0dcf9"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.0+0/libtakum.v0.5.0.x86_64-linux-gnu.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "5272c54b84a0f4a8195ac4584c3ffd231fb16ae7"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "2e25cc3173800f3b72349ebdc48668433059451ef71d230bca5fe380a259a892"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.0+0/libtakum.v0.5.0.x86_64-linux-musl.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "9f6058048ce4e984d9560a65f8e7fe34cc5bc063"
os = "freebsd"

    [[libtakum.download]]
    sha256 = "b83e65fcb349b72c9d51448e0e85ae597264b4397c8eb8fd183f346ca5ad74d0"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.0+0/libtakum.v0.5.0.x86_64-unknown-freebsd.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "acf0513b427e521a96af94dec8bd15f9090eaf1b"
os = "windows"

    [[libtakum.download]]
    sha256 = "878f930fa4c8231c8f3ef1147d41d254b2eacb810bd01e697d200a1b50c429aa"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.5.0+0/libtakum.v0.5.0.x86_64-w64-mingw32.tar.gz"
