[[libtakum]]
arch = "aarch64"
git-tree-sha1 = "01ab83241b60340635d3d90969138ffa901b89d4"
os = "macos"

    [[libtakum.download]]
    sha256 = "18d88a0cdecc5adf0899d6da88414d6b17dc27f110168053c4389d5227e9b5e7"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.0+0/libtakum.v0.2.0.aarch64-apple-darwin.tar.gz"
[[libtakum]]
arch = "aarch64"
git-tree-sha1 = "e433921159362cd3d2c16596ca7641126e929950"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "bfac5f0638ef883ba01cbbb63643a1583f3530dbbeaf6692c194ca6337f23974"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.0+0/libtakum.v0.2.0.aarch64-linux-gnu.tar.gz"
[[libtakum]]
arch = "aarch64"
git-tree-sha1 = "6076a6e14ed384dbe4b05c02e20cdb82c8fe2e9d"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "005e14c0a92eed3cd2ca7b9160e5faa2cc2cf68af15146cd0e93ae780899e7af"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.0+0/libtakum.v0.2.0.aarch64-linux-musl.tar.gz"
[[libtakum]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a45505d63a7b29e796567820bed41e3bfaa7577e"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "f9903f37bcc9deef6ee4ffb8df061df56ba9d0a2f431361e34d89da1b57658b2"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.0+0/libtakum.v0.2.0.armv6l-linux-gnueabihf.tar.gz"
[[libtakum]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "78b7bd5fb0a5adee0d96846e2cd7807dc582e863"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "64c36690720f8c1d921ec2e1f87abdba44cc6388fa4cf34379e0ca21b97a2230"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.0+0/libtakum.v0.2.0.armv6l-linux-musleabihf.tar.gz"
[[libtakum]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3afde8fbdfee474cfc901576276d2b247d699971"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "99e84d6f4b142ea14f9dbdd6c4c77ae028988d18d16a4a204ba54d554df94bfb"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.0+0/libtakum.v0.2.0.armv7l-linux-gnueabihf.tar.gz"
[[libtakum]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "132f7abb298d1bd7b1d196fe29690d7d8c5501d0"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "8b133f1fd94c82d6b3994fcbf628cfebe3d7deba7315c6629e24102537267b57"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.0+0/libtakum.v0.2.0.armv7l-linux-musleabihf.tar.gz"
[[libtakum]]
arch = "i686"
git-tree-sha1 = "df46a188c90d46f36c1e7820a30d11e3d9bfd396"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "2a295f2b9b713c0a12d2579cca2ea4c0464404a051b51f105ab0f9d04852f2a2"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.0+0/libtakum.v0.2.0.i686-linux-gnu.tar.gz"
[[libtakum]]
arch = "i686"
git-tree-sha1 = "0b377385e9aa9b735b984757985290b0b75e6654"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "8fea4df3b8059ea06e663dd2cca5dda9a8d33cb60c8b74f5bc5a6c1f930d2bed"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.0+0/libtakum.v0.2.0.i686-linux-musl.tar.gz"
[[libtakum]]
arch = "i686"
git-tree-sha1 = "04ecad949241dad76f941010845933fc4b5b0abd"
os = "windows"

    [[libtakum.download]]
    sha256 = "0de3c649119f4f5412ccd99d63a69babbbf4c593f272a5e97dd12718aaee7fb4"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.0+0/libtakum.v0.2.0.i686-w64-mingw32.tar.gz"
[[libtakum]]
arch = "powerpc64le"
git-tree-sha1 = "f685408e213e78d0c36e80f926a0e1f04799dcde"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "d8b785d0f8cf4c66014952dc7a78ebdbc02e0998f7f74eaae9b61a0b53c7cef0"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.0+0/libtakum.v0.2.0.powerpc64le-linux-gnu.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "64584e613d9fcb99b0e3f04876d70eb7f6040845"
os = "macos"

    [[libtakum.download]]
    sha256 = "1cac9117722567ec7d966b0dc24f29533a246329074af18feef31543aa4d91c0"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.0+0/libtakum.v0.2.0.x86_64-apple-darwin.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "3f7d89dbd25eecc49691306a8474e198843cc0c1"
libc = "glibc"
os = "linux"

    [[libtakum.download]]
    sha256 = "cf793287ff88564b7f08eaf0a006e8c851feba63ff4e53d9ce4680bd949c3148"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.0+0/libtakum.v0.2.0.x86_64-linux-gnu.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "663e74f09096acef781bbf72008887156131c4fe"
libc = "musl"
os = "linux"

    [[libtakum.download]]
    sha256 = "79f36fc67cdfc0c15850325dfeca4f74a8791aa45023e7aefe5ba40a6e760dbd"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.0+0/libtakum.v0.2.0.x86_64-linux-musl.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "22dd87cc8618fff0f99b701f6c2b90c091e370ea"
os = "freebsd"

    [[libtakum.download]]
    sha256 = "ce8c5ffe72179d5801498446dee278bd5c9178e257fe124d98490068137f825e"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.0+0/libtakum.v0.2.0.x86_64-unknown-freebsd.tar.gz"
[[libtakum]]
arch = "x86_64"
git-tree-sha1 = "4d0594f3767848177101ea000eab2cb12866172a"
os = "windows"

    [[libtakum.download]]
    sha256 = "b01ba87b44db2b4ccf4d00e10b005e3a85122a8c0d2fc2e12a617ca8c17987c7"
    url = "https://github.com/JuliaBinaryWrappers/libtakum_jll.jl/releases/download/libtakum-v0.2.0+0/libtakum.v0.2.0.x86_64-w64-mingw32.tar.gz"
